# Generated by Django 3.0.2 on 2020-10-14 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_marathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningsession',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
