# Generated by Django 3.0.2 on 2020-10-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_marathon', '0002_auto_20201014_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningsession',
            old_name='id',
            new_name='sessionId',
        ),
    ]
